version: "3"
# this file uses prebuilt image in dockerhub
services:
  jekyll:
    image: jekyll/builder:latest # jekyll/builder:latest
    build: .
    ports:
      - 8080:8080
      - 35729:35729
    volumes:
      - .:/srv/jekyll
    environment:
      JEKYLL_UID: 1001
      JEKYLL_GID: 1001
    command: jekyll serve --force_polling --drafts
